// tracker-data.js — seed content for The Proof Lab. Edit freely; your live
// edits are kept in localStorage, this file only seeds the first visit.
window.TRACKER_SEED = [
  {
    id: 'algtop', name: 'Algebraic Topology', glyph: 'π₁', nickname: 'Alg Top',
    assignments: [
      { id: 'at1', title: 'Problem Set 3 — Van Kampen & pushouts', due: '2026-08-10', status: 'doing' },
      { id: 'at2', title: 'Problem Set 4 — CW complexes', due: '2026-08-24', status: 'todo' },
      { id: 'at3', title: 'Problem Set 2 — Homotopy lifting', due: '2026-07-28', status: 'done' },
    ],
    theorems: [
      { id: 'att1', type: 'Theorem', name: "Van Kampen's Theorem", statement: 'If $X = U \\cup V$ with $U, V$ open and path-connected and $U \\cap V$ path-connected, then $\\pi_1(X) \\cong \\pi_1(U) *_{\\pi_1(U\\cap V)} \\pi_1(V)$.', proof: 'Build the pushout of groupoids induced by the cover, then pass to fundamental groups — the amalgam records loops that stay in $U$, stay in $V$, or cross through $U \\cap V$.', revealed: false },
      { id: 'att2', type: 'Lemma', name: 'Fundamental group of the circle', statement: '$\\pi_1(S^1) \\cong \\mathbb{Z}$, generated by the loop winding once around.', proof: 'Use the covering $p: \\mathbb{R} \\to S^1$, $t \\mapsto e^{2\\pi i t}$; paths and homotopies lift uniquely, and the winding number gives the isomorphism.', revealed: false },
      { id: 'att3', type: 'Definition', name: 'CW complex', statement: 'A space built inductively by attaching $n$-cells $D^n$ along maps $\\partial D^n \\to X^{(n-1)}$.', proof: 'Key idea: the cellular structure lets homology be computed from a chain complex on the free abelian groups generated by the cells.', revealed: false },
    ],
    problems: [
      { id: 'atp1', title: 'Compute $\\pi_1$ of the figure-eight', problem: 'Show the wedge of two circles has fundamental group the free group $F_2$.', solution: 'Cover by two open sets, each deformation-retracting to one circle, overlapping in a contractible neighbourhood of the wedge point. Van Kampen gives $\\mathbb{Z} * \\mathbb{Z} = F_2$.', revealed: false },
      { id: 'atp2', title: 'Non-orientable surface', problem: 'Compute $\\pi_1(\\mathbb{RP}^2)$.', solution: '$S^2 \\to \\mathbb{RP}^2$ is a degree-2 cover with deck group $\\mathbb{Z}/2$; since $S^2$ is simply connected, $\\pi_1(\\mathbb{RP}^2) \\cong \\mathbb{Z}/2$.', revealed: false },
    ],
    notes: [
      { id: 'atn1', text: "Keep re-deriving van Kampen from the groupoid version until it's obvious why $U \\cap V$ needs to be connected — the group version hides it.", date: '2026-07-20' },
    ],
    chapters: [],
  },
  {
    id: 'meastheory', name: 'Measure Theory', glyph: '∫dμ', nickname: 'Measure',
    assignments: [
      { id: 'mt1', title: 'Problem Set 2 — Outer measures', due: '2026-08-05', status: 'todo' },
      { id: 'mt2', title: 'Problem Set 1 — σ-algebras', due: '2026-07-27', status: 'doing' },
    ],
    theorems: [
      { id: 'mtt1', type: 'Theorem', name: 'Carathéodory Extension Theorem', statement: 'A premeasure $\\mu_0$ on an algebra $\\mathcal{A}$ extends to a measure on $\\sigma(\\mathcal{A})$.', proof: 'Define an outer measure $\\mu^*$ via countable covers by elements of $\\mathcal{A}$; the $\\mu^*$-measurable sets (Carathéodory criterion) form a $\\sigma$-algebra on which $\\mu^*$ is countably additive.', revealed: false },
      { id: 'mtt2', type: 'Theorem', name: 'Dominated Convergence Theorem', statement: 'If $f_n \\to f$ a.e. and $|f_n| \\le g$ with $g$ integrable, then $\\int f_n \\to \\int f$.', proof: "Apply Fatou's lemma to $g - f_n$ and $g + f_n$ at once, squeezing $\\int f$ between $\\liminf$ and $\\limsup$ of $\\int f_n$.", revealed: false },
      { id: 'mtt3', type: 'Lemma', name: "Fatou's Lemma", statement: 'For nonnegative measurable $f_n$, $\\int \\liminf f_n \\le \\liminf \\int f_n$.', proof: 'Key idea: apply monotone convergence to $g_n = \\inf_{k \\ge n} f_k$, which increases to $\\liminf f_n$.', revealed: false },
    ],
    problems: [
      { id: 'mtp1', title: 'Non-measurable set', problem: 'Construct a subset of $[0,1]$ that is not Lebesgue measurable.', solution: "Vitali's construction: choose one representative from each coset of $\\mathbb{Q}$ in $[0,1)$ under mod-1 addition via the axiom of choice; translation-invariance plus countable additivity contradict measurability.", revealed: false },
    ],
    notes: [],
    chapters: [],
  },
  {
    id: 'chern', name: 'Chern Classes — Research', glyph: 'c(E)', nickname: 'Chern',
    assignments: [
      { id: 'ch1', title: 'Read Milnor–Stasheff ch. 14', due: '2026-08-01', status: 'todo' },
      { id: 'ch2', title: 'Draft: splitting principle writeup', due: '2026-08-15', status: 'todo' },
      { id: 'ch3', title: 'Meeting notes — advisor check-in', due: '2026-07-25', status: 'doing' },
    ],
    theorems: [
      { id: 'cht1', type: 'Fact', name: 'Whitney Sum Formula', statement: '$c(E \\oplus F) = c(E) \\smile c(F)$ in $H^*(X)$.', proof: 'Follows from the splitting principle: pull back to a space where both bundles split into line bundles, where the formula is a product of first Chern classes.', revealed: false },
      { id: 'cht2', type: 'Fact', name: 'Splitting Principle', statement: 'For a vector bundle $E \\to X$ there is $f: F(E) \\to X$ with $f^*$ injective on cohomology and $f^*E$ a sum of line bundles.', proof: 'Key idea: build $F(E)$ as the flag bundle of $E$; Leray–Hirsch gives the injectivity.', revealed: false },
    ],
    problems: [],
    notes: [
      { id: 'chn1', text: 'Research thread: does the splitting-principle argument generalise cleanly to equivariant Chern classes? Ask advisor Tuesday.', date: '2026-07-22' },
    ],
    chapters: [],
  },
];
