// lib/fitness/exerciseCatalog.js — the canonical Exercise database. This is
// the core of the workout architecture: a workout no longer embeds a bare
// exercise name + hand-picked equipment ids (the old model). Instead, a
// WorkoutExercise just references one of these by `exerciseId`, and
// everything else -- target muscles, movement pattern, required equipment,
// a demo GIF, instructions -- comes from here automatically.
//
// Sourced from Anatome's bundled free-exercise-db dataset (MIT/Unlicense,
// see https://github.com/NextSolutionsStudio/anatome and
// https://github.com/yuhonas/free-exercise-db) rather than a live API call:
// that dataset is static and versioned, so treating it as *seed data authored
// once* is both more reliable (works even if api.anatome.dev is down -- see
// gifUrl() below, which is the only live network dependency, and even that
// degrades gracefully) and easier to keep correct than re-deriving it from a
// runtime fetch every time. `apiExerciseId` is the free-exercise-db ext_id,
// kept around so a demo GIF can be constructed from Anatome's hosted,
// license-cleared /exerciseGif endpoint without bundling any media here.
//
// `equipmentSlots` is an array of "slots"; every slot must have at least one
// option present at a gym for the exercise to count as available there. Most
// exercises have exactly one slot with one or more interchangeable options
// (e.g. lat pulldown: one slot, several machine types that all work equally
// well). A compound exercise like barbell bench press genuinely needs two
// *different* things at once (a barbell AND a bench), so it gets two slots.
// This is what keeps "required equipment" and "compatible equipment" from
// collapsing into the same flat, ambiguous list -- see equipmentCatalog.js
// for what each id refers to. The first option in each slot is the
// "canonical" one shown in compact UI; the rest only matter for the
// gym-availability check.
export const BODY_PARTS = [
  { id: 'chest', label: 'Chest' },
  { id: 'back', label: 'Back' },
  { id: 'shoulders', label: 'Shoulders' },
  { id: 'biceps', label: 'Biceps' },
  { id: 'triceps', label: 'Triceps' },
  { id: 'legs', label: 'Legs' },
  { id: 'core', label: 'Core' },
];

export const MOVEMENT_PATTERNS = ['push', 'pull', 'squat', 'hinge', 'isolation', 'compound', 'core'];

// `gymGifsId` is a "{muscle}/{slug}" id into ExerciseGymGifsDB (see
// exerciseMedia.js) -- a real multi-frame animated demo GIF, unlike
// Anatome's `apiExerciseId` media which (per Anatome's own source) is just
// a 2-frame photo flip. Where both are set, exerciseGifUrl() prefers
// gymGifsId; apiExerciseId still always drives the muscle diagram and
// remains the fallback demo media when an exercise has no gymGifsId match.
function ex({
  id, canonicalName, aliases = [], bodyParts, primaryMuscles, secondaryMuscles = [],
  movementPattern, equipmentSlots, instructions, apiExerciseId, gymGifsId,
}) {
  return {
    id,
    canonicalName,
    aliases,
    bodyParts,
    primaryMuscles,
    secondaryMuscles,
    movementPattern,
    equipmentSlots,
    instructions,
    demoMedia: apiExerciseId ? { source: 'anatome', apiExerciseId } : null,
    apiSource: apiExerciseId ? 'anatome' : 'custom',
    apiExerciseId: apiExerciseId || null,
    gymGifsId: gymGifsId || null,
    custom: false,
  };
}

export const EXERCISE_CATALOG = [
  // ---------- Push ----------
  ex({
    id: 'barbell-bench-press',
    canonicalName: 'Barbell Bench Press',
    aliases: ['bench press', 'flat bench', 'bb bench press'],
    bodyParts: ['chest'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    movementPattern: 'push',
    equipmentSlots: [['barbells', 'olympic-barbell'], ['flat-bench', 'adjustable-bench']],
    instructions: [
      'Lie back on the bench, feet flat on the floor.',
      'Grip the bar slightly wider than shoulder width.',
      'Lower the bar to your mid-chest under control.',
      'Press back up to full arm extension.',
    ],
    apiExerciseId: 'Barbell_Bench_Press_-_Medium_Grip',
    gymGifsId: 'pectorals/barbell-bench-press',
  }),
  ex({
    id: 'incline-dumbbell-press',
    canonicalName: 'Incline Dumbbell Press',
    aliases: ['incline db press', 'incline press'],
    bodyParts: ['chest'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    movementPattern: 'push',
    equipmentSlots: [['dumbbells', 'adjustable-dumbbells'], ['incline-bench']],
    instructions: [
      'Set the bench to a 30-45° incline.',
      'Press the dumbbells up over your upper chest.',
      'Lower with control until your upper arms are about parallel to the floor.',
      'Press back up without locking out hard at the top.',
    ],
    apiExerciseId: 'Incline_Dumbbell_Press',
    gymGifsId: 'pectorals/dumbbell-incline-bench-press',
  }),
  ex({
    id: 'pec-deck-fly',
    canonicalName: 'Pec Deck / Chest Fly',
    aliases: ['chest fly', 'pec deck', 'butterfly', 'machine fly'],
    bodyParts: ['chest'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    movementPattern: 'isolation',
    equipmentSlots: [['pec-deck', 'chest-fly-machine', 'cable-crossover']],
    instructions: [
      'Sit tall with your back against the pad.',
      'Grip the handles with a slight bend in your elbows.',
      'Bring your hands together in front of your chest.',
      'Return slowly until you feel a stretch across the chest.',
    ],
    apiExerciseId: 'Butterfly',
    gymGifsId: 'pectorals/lever-seated-fly',
  }),
  ex({
    id: 'shoulder-press',
    canonicalName: 'Shoulder Press',
    aliases: ['overhead press', 'ohp', 'military press', 'dumbbell shoulder press'],
    bodyParts: ['shoulders'],
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    movementPattern: 'push',
    equipmentSlots: [['shoulder-press-machine', 'plate-loaded-shoulder-press', 'dumbbells']],
    instructions: [
      'Sit with back supported, handles at shoulder height.',
      'Press straight up until arms are extended without locking hard.',
      'Lower back to shoulder height under control.',
    ],
    apiExerciseId: 'Dumbbell_Shoulder_Press',
    gymGifsId: 'delts/dumbbell-seated-shoulder-press',
  }),
  ex({
    id: 'lateral-raise',
    canonicalName: 'Lateral Raise',
    aliases: ['side raise', 'side lateral raise', 'db lateral raise'],
    bodyParts: ['shoulders'],
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    movementPattern: 'isolation',
    equipmentSlots: [['dumbbells', 'lateral-raise-machine', 'cable-lateral-raise-station']],
    instructions: [
      'Stand holding a dumbbell in each hand at your sides.',
      'Raise your arms out to the sides to about shoulder height.',
      'Lower with control -- don’t swing or use momentum.',
    ],
    apiExerciseId: 'Side_Lateral_Raise',
    gymGifsId: 'delts/dumbbell-lateral-raise',
  }),
  ex({
    id: 'triceps-pushdown',
    canonicalName: 'Triceps Pushdown',
    aliases: ['cable pushdown', 'rope pushdown', 'tricep pushdown'],
    bodyParts: ['triceps'],
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    movementPattern: 'isolation',
    equipmentSlots: [['cable-pushdown-station']],
    instructions: [
      'Grip the attachment with elbows tucked at your sides.',
      'Push down until your arms are fully extended.',
      'Let the weight return slowly without flaring your elbows out.',
    ],
    apiExerciseId: 'Triceps_Pushdown',
    gymGifsId: 'triceps/cable-pushdown',
  }),
  ex({
    id: 'overhead-triceps-extension',
    canonicalName: 'Overhead Triceps Extension',
    aliases: ['overhead extension', 'skull crusher overhead', 'french press'],
    bodyParts: ['triceps'],
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    movementPattern: 'isolation',
    equipmentSlots: [['cable-pushdown-station', 'dumbbells']],
    instructions: [
      'Hold the rope or dumbbell behind your head, elbows pointed up.',
      'Extend your arms overhead until straight.',
      'Lower back behind your head under control.',
    ],
    apiExerciseId: 'Cable_Rope_Overhead_Triceps_Extension',
    gymGifsId: 'triceps/cable-rope-high-pulley-overhead-tricep-extension',
  }),

  // ---------- Pull ----------
  ex({
    id: 'lat-pulldown',
    canonicalName: 'Lat Pulldown',
    aliases: ['pulldown', 'wide grip pulldown', 'cable pulldown'],
    bodyParts: ['back'],
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    movementPattern: 'pull',
    equipmentSlots: [['lat-pulldown', 'functional-trainer', 'dual-adjustable-pulley']],
    instructions: [
      'Grip the bar wider than shoulder width, sit with thighs secured.',
      'Pull the bar down to your upper chest, driving elbows down and back.',
      'Control the bar back up to full arm extension.',
    ],
    apiExerciseId: 'Wide-Grip_Lat_Pulldown',
    gymGifsId: 'lats/cable-pulldown',
  }),
  ex({
    id: 'seated-cable-row',
    canonicalName: 'Seated Cable Row',
    aliases: ['cable row', 'seated row', 'low row'],
    bodyParts: ['back'],
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    movementPattern: 'pull',
    equipmentSlots: [['seated-cable-row', 'low-row', 'functional-trainer']],
    instructions: [
      'Sit with knees slightly bent, grip the handle, back straight.',
      'Pull the handle to your torso, squeezing your shoulder blades together.',
      'Extend your arms back out under control.',
    ],
    apiExerciseId: 'Seated_Cable_Rows',
    gymGifsId: 'upper-back/cable-seated-row',
  }),
  ex({
    id: 'chest-supported-row',
    canonicalName: 'Chest Supported Row',
    aliases: ['t-bar row', 'chest supported t-bar row', 'machine row'],
    bodyParts: ['back'],
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    movementPattern: 'pull',
    equipmentSlots: [['chest-supported-row', 't-bar-row', 'iso-lateral-row', 'plate-loaded-row']],
    instructions: [
      'Lie chest-down on the support pad, grip the handles.',
      'Row the weight up, squeezing your back at the top.',
      'Lower under control to a full stretch.',
    ],
    apiExerciseId: 'Lying_T-Bar_Row',
    gymGifsId: 'upper-back/lever-t-bar-row',
  }),
  ex({
    id: 'reverse-pec-deck',
    canonicalName: 'Reverse Pec Deck / Rear Delt Fly',
    aliases: ['rear delt fly', 'reverse fly', 'reverse pec deck', 'rear delt machine'],
    bodyParts: ['shoulders'],
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    movementPattern: 'isolation',
    equipmentSlots: [['reverse-pec-deck', 'cable-lateral-raise-station', 'dumbbells']],
    instructions: [
      'Sit facing the pad, chest against it, grip the handles.',
      'Pull your arms out and back, squeezing your rear shoulders.',
      'Return slowly to the start.',
    ],
    apiExerciseId: 'Reverse_Machine_Flyes',
    gymGifsId: 'delts/lever-seated-reverse-fly',
  }),
  ex({
    id: 'biceps-curl',
    canonicalName: 'Biceps Curl',
    aliases: ['bicep curl', 'dumbbell curl', 'db curl'],
    bodyParts: ['biceps'],
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    movementPattern: 'isolation',
    equipmentSlots: [['dumbbells', 'barbells', 'cable-curl-station', 'biceps-curl-machine']],
    instructions: [
      'Stand holding weights at your sides, elbows tucked in.',
      'Curl up toward your shoulders without swinging.',
      'Lower slowly back to full extension.',
    ],
    apiExerciseId: 'Dumbbell_Bicep_Curl',
    gymGifsId: 'biceps/dumbbell-biceps-curl',
  }),
  ex({
    id: 'hammer-curl',
    canonicalName: 'Hammer Curl',
    aliases: ['neutral grip curl', 'db hammer curl'],
    bodyParts: ['biceps'],
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    movementPattern: 'isolation',
    equipmentSlots: [['dumbbells']],
    instructions: [
      'Hold dumbbells with palms facing each other.',
      'Curl up keeping that neutral grip throughout.',
      'Lower with control.',
    ],
    apiExerciseId: 'Hammer_Curls',
    gymGifsId: 'biceps/dumbbell-hammer-curl',
  }),
  ex({
    id: 'reverse-curl',
    canonicalName: 'Forearm Curl / Reverse Curl',
    aliases: ['reverse curl', 'forearm curl', 'wrist curl'],
    bodyParts: ['biceps'],
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['biceps'],
    movementPattern: 'isolation',
    equipmentSlots: [['dumbbells', 'ez-curl-bar', 'barbells']],
    instructions: [
      'Hold the bar or dumbbells with an overhand (palms-down) grip.',
      'Curl up using just your forearms/wrists.',
      'Lower slowly under control.',
    ],
    apiExerciseId: 'Standing_Dumbbell_Reverse_Curl',
    gymGifsId: 'biceps/dumbbell-standing-reverse-curl',
  }),

  // ---------- Legs ----------
  ex({
    id: 'hack-squat',
    canonicalName: 'Hack Squat',
    aliases: ['machine squat'],
    bodyParts: ['legs'],
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    movementPattern: 'squat',
    equipmentSlots: [['hack-squat', 'pendulum-squat', 'v-squat']],
    instructions: [
      'Set your shoulders and back against the pads, feet shoulder width.',
      'Release the safety and squat down until thighs are about parallel.',
      'Drive back up through your heels.',
    ],
    apiExerciseId: 'Hack_Squat',
    gymGifsId: 'glutes/sled-hack-squat',
  }),
  ex({
    id: 'leg-press',
    canonicalName: 'Leg Press',
    aliases: ['45 degree leg press', 'sled press'],
    bodyParts: ['legs'],
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    movementPattern: 'squat',
    equipmentSlots: [['leg-press', 'horizontal-leg-press', '45-degree-leg-press']],
    instructions: [
      'Sit with feet shoulder width on the platform.',
      'Lower the sled until your knees reach about 90°.',
      'Press back up without locking your knees out hard.',
    ],
    apiExerciseId: 'Leg_Press',
    gymGifsId: 'glutes/sled-45-leg-press',
  }),
  ex({
    id: 'leg-extension',
    canonicalName: 'Leg Extension',
    aliases: ['quad extension'],
    bodyParts: ['legs'],
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    movementPattern: 'isolation',
    equipmentSlots: [['leg-extension']],
    instructions: [
      'Sit with the pad resting on your lower shins.',
      'Extend your legs until straight, squeezing your quads.',
      'Lower with control.',
    ],
    apiExerciseId: 'Leg_Extensions',
    gymGifsId: 'quads/lever-leg-extension',
  }),
  ex({
    id: 'seated-leg-curl',
    canonicalName: 'Seated Leg Curl',
    aliases: ['leg curl', 'hamstring curl', 'lying leg curl'],
    bodyParts: ['legs'],
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    movementPattern: 'isolation',
    equipmentSlots: [['seated-leg-curl', 'lying-leg-curl', 'standing-leg-curl']],
    instructions: [
      'Sit with the pad against the back of your lower legs.',
      'Curl your heels down and back, squeezing your hamstrings.',
      'Return with control.',
    ],
    apiExerciseId: 'Seated_Leg_Curl',
    gymGifsId: 'hamstrings/lever-seated-leg-curl',
  }),
  ex({
    id: 'hip-abduction',
    canonicalName: 'Hip Abduction',
    aliases: ['thigh abductor', 'outer thigh machine'],
    bodyParts: ['legs'],
    primaryMuscles: ['glutes'],
    secondaryMuscles: [],
    movementPattern: 'isolation',
    equipmentSlots: [['hip-abduction']],
    instructions: [
      'Sit with legs against the pads.',
      'Push your legs outward against the resistance.',
      'Return with control.',
    ],
    apiExerciseId: 'Thigh_Abductor',
    gymGifsId: 'abductors/lever-seated-hip-abduction',
  }),
  ex({
    id: 'calf-raise',
    canonicalName: 'Calf Raise',
    aliases: ['standing calf raise', 'seated calf raise'],
    bodyParts: ['legs'],
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    movementPattern: 'isolation',
    equipmentSlots: [['calf-raise-machine', 'seated-calf-raise', 'standing-calf-raise']],
    instructions: [
      'Position your shoulders/thighs under the pads, balls of your feet on the platform.',
      'Rise up onto your toes as high as you can.',
      'Lower until you feel a stretch, then repeat.',
    ],
    apiExerciseId: 'Standing_Calf_Raises',
    gymGifsId: 'calves/lever-standing-calf-raise',
  }),

  // ---------- Upper (extra) ----------
  ex({
    id: 'incline-chest-press-machine-ex',
    canonicalName: 'Incline Chest Press',
    aliases: ['machine incline press', 'incline press machine'],
    bodyParts: ['chest'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    movementPattern: 'push',
    equipmentSlots: [['incline-chest-press-machine']],
    instructions: [
      'Sit with your back against the pad, grips at chest height.',
      'Press up and forward until your arms extend.',
      'Return with control.',
    ],
    apiExerciseId: 'Leverage_Incline_Chest_Press',
    gymGifsId: 'pectorals/lever-incline-chest-press',
  }),

  // ---------- Lower + Core (extra) ----------
  ex({
    id: 'romanian-deadlift',
    canonicalName: 'Romanian Deadlift',
    aliases: ['rdl', 'stiff leg deadlift'],
    bodyParts: ['legs'],
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'lower-back'],
    movementPattern: 'hinge',
    equipmentSlots: [['barbells', 'olympic-barbell', 'trap-bar', 'dumbbells']],
    instructions: [
      'Hold the bar in front of your thighs, feet hip width.',
      'Push your hips back, lowering the bar along your legs with a slight knee bend.',
      'Feel a stretch in your hamstrings, then drive your hips forward to stand.',
    ],
    apiExerciseId: 'Romanian_Deadlift',
    gymGifsId: 'glutes/barbell-romanian-deadlift',
  }),
  ex({
    id: 'cable-crunch',
    canonicalName: 'Cable Crunch',
    aliases: ['ab crunch', 'kneeling cable crunch'],
    bodyParts: ['core'],
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    movementPattern: 'core',
    equipmentSlots: [['cable-station', 'cable-crossover', 'adjustable-cable-machine']],
    instructions: [
      'Kneel below the cable, rope behind your head.',
      'Crunch down, bringing your elbows toward your knees.',
      'Return with control, keeping tension on your abs.',
    ],
    apiExerciseId: 'Cable_Crunch',
    gymGifsId: 'abs/cable-kneeling-crunch',
  }),
  ex({
    id: 'hanging-leg-raise',
    canonicalName: 'Hanging Knee/Leg Raise',
    aliases: ['hanging leg raise', 'hanging knee raise', 'captains chair raise'],
    bodyParts: ['core'],
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    movementPattern: 'core',
    equipmentSlots: [['pullup-bar', 'captains-chair', 'roman-chair']],
    instructions: [
      'Hang from the bar (or use the captain’s chair supports).',
      'Raise your knees or legs up toward your chest.',
      'Lower with control, avoiding swinging.',
    ],
    apiExerciseId: 'Hanging_Leg_Raise',
    gymGifsId: 'abs/hanging-leg-raise',
  }),
  ex({
    id: 'plank',
    canonicalName: 'Plank',
    aliases: ['front plank', 'forearm plank'],
    bodyParts: ['core'],
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    movementPattern: 'core',
    equipmentSlots: [],
    instructions: [
      'Support yourself on your forearms and toes, body in a straight line.',
      'Brace your core and hold, keeping hips level.',
    ],
    apiExerciseId: 'Plank',
  }),

  // ---------- Extra library exercises (search variety, not in the fixed program) ----------
  ex({
    id: 'barbell-squat',
    canonicalName: 'Barbell Back Squat',
    aliases: ['squat', 'back squat', 'bb squat'],
    bodyParts: ['legs'],
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    movementPattern: 'squat',
    equipmentSlots: [['squat-rack', 'power-rack'], ['barbells', 'olympic-barbell']],
    instructions: [
      'Set the bar across your upper back, unrack, and step back.',
      'Squat down until your hips drop below your knees.',
      'Drive back up through your whole foot.',
    ],
    apiExerciseId: 'Barbell_Full_Squat',
    gymGifsId: 'glutes/barbell-full-squat',
  }),
  ex({
    id: 'smith-machine-squat',
    canonicalName: 'Smith Machine Squat',
    aliases: ['smith squat'],
    bodyParts: ['legs'],
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    movementPattern: 'squat',
    equipmentSlots: [['smith-machine']],
    instructions: [
      'Position the bar across your upper back, unrack it.',
      'Squat down under control, guided by the fixed bar path.',
      'Drive back up to standing.',
    ],
    apiExerciseId: 'Smith_Machine_Squat',
    gymGifsId: 'glutes/smith-full-squat',
  }),
  ex({
    id: 'goblet-squat',
    canonicalName: 'Goblet Squat',
    aliases: ['db squat', 'dumbbell squat'],
    bodyParts: ['legs'],
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    movementPattern: 'squat',
    equipmentSlots: [['dumbbells', 'kettlebells']],
    instructions: [
      'Hold a dumbbell or kettlebell vertically at your chest.',
      'Squat down between your knees, keeping your torso upright.',
      'Drive back up to standing.',
    ],
    apiExerciseId: 'Dumbbell_Squat',
    gymGifsId: 'quads/dumbbell-goblet-squat',
  }),
  ex({
    id: 'bulgarian-split-squat',
    canonicalName: 'Bulgarian Split Squat',
    aliases: ['rear foot elevated split squat', 'rfess'],
    bodyParts: ['legs'],
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    movementPattern: 'squat',
    equipmentSlots: [['flat-bench', 'adjustable-bench'], ['dumbbells']],
    instructions: [
      'Rest one foot behind you on a bench, holding dumbbells at your sides.',
      'Lower your back knee toward the floor.',
      'Drive up through your front foot.',
    ],
    apiExerciseId: 'Split_Squat_with_Dumbbells',
    gymGifsId: 'quads/dumbbell-single-leg-split-squat',
  }),
  ex({
    id: 'conventional-deadlift',
    canonicalName: 'Conventional Deadlift',
    aliases: ['deadlift'],
    bodyParts: ['legs'],
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'lower-back', 'back'],
    movementPattern: 'hinge',
    equipmentSlots: [['barbells', 'olympic-barbell']],
    instructions: [
      'Stand with the bar over mid-foot, grip just outside your legs.',
      'Brace, flatten your back, and drive through the floor to stand.',
      'Lower the bar back down under control.',
    ],
    apiExerciseId: 'Barbell_Deadlift',
    gymGifsId: 'glutes/barbell-deadlift',
  }),
  ex({
    id: 'pull-up',
    canonicalName: 'Pull-Up',
    aliases: ['pullup', 'chin up'],
    bodyParts: ['back'],
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    movementPattern: 'pull',
    equipmentSlots: [['pullup-bar']],
    instructions: [
      'Hang from the bar with an overhand grip, wider than shoulders.',
      'Pull yourself up until your chin clears the bar.',
      'Lower with control to full arm extension.',
    ],
    apiExerciseId: 'Pullups',
    gymGifsId: 'lats/pull-up',
  }),
  ex({
    id: 'assisted-pull-up',
    canonicalName: 'Assisted Pull-Up',
    aliases: ['assisted pullup', 'band assisted pull up'],
    bodyParts: ['back'],
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    movementPattern: 'pull',
    equipmentSlots: [['assisted-pullup-machine', 'assisted-pullup-dip']],
    instructions: [
      'Kneel or stand on the platform with the counterweight set.',
      'Pull yourself up until your chin clears the handles.',
      'Lower with control.',
    ],
    apiExerciseId: 'Band_Assisted_Pull-Up',
    gymGifsId: 'lats/assisted-pull-up',
  }),
  ex({
    id: 'push-up',
    canonicalName: 'Push-Up',
    aliases: ['pushup'],
    bodyParts: ['chest'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    movementPattern: 'push',
    equipmentSlots: [],
    instructions: [
      'Start in a plank position, hands under shoulders.',
      'Lower your chest to the floor.',
      'Push back up to full arm extension.',
    ],
    apiExerciseId: 'Pushups',
    gymGifsId: 'pectorals/push-up',
  }),
  ex({
    id: 'dip',
    canonicalName: 'Dip',
    aliases: ['tricep dip', 'chest dip'],
    bodyParts: ['triceps'],
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    movementPattern: 'push',
    equipmentSlots: [['dip-station', 'parallel-bars']],
    instructions: [
      'Support yourself on the bars, arms extended.',
      'Lower your body until your elbows reach about 90°.',
      'Press back up to full extension.',
    ],
    apiExerciseId: 'Dips_-_Triceps_Version',
    gymGifsId: 'triceps/triceps-dip',
  }),
  ex({
    id: 'face-pull',
    canonicalName: 'Face Pull',
    aliases: [],
    bodyParts: ['shoulders'],
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    movementPattern: 'pull',
    equipmentSlots: [['cable-station', 'adjustable-cable-machine', 'functional-trainer']],
    instructions: [
      'Set the rope at upper-chest height.',
      'Pull toward your face, flaring your elbows out wide.',
      'Return with control.',
    ],
    apiExerciseId: 'Cable_Rope_Rear-Delt_Rows',
  }),
  ex({
    id: 'preacher-curl',
    canonicalName: 'Preacher Curl',
    aliases: [],
    bodyParts: ['biceps'],
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    movementPattern: 'isolation',
    equipmentSlots: [['preacher-curl-machine', 'preacher-curl-bench']],
    instructions: [
      'Rest your upper arms on the pad.',
      'Curl the weight up, squeezing your biceps.',
      'Lower slowly to a full stretch.',
    ],
    apiExerciseId: 'Preacher_Curl',
    gymGifsId: 'biceps/barbell-preacher-curl',
  }),
  ex({
    id: 'skull-crusher',
    canonicalName: 'Skull Crusher',
    aliases: ['lying triceps extension'],
    bodyParts: ['triceps'],
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    movementPattern: 'isolation',
    equipmentSlots: [['ez-curl-bar', 'dumbbells'], ['flat-bench']],
    instructions: [
      'Lie on the bench holding the bar/dumbbells above your chest.',
      'Bend your elbows to lower the weight toward your forehead.',
      'Extend back up without flaring your elbows.',
    ],
    apiExerciseId: 'Lying_Triceps_Press',
    gymGifsId: 'triceps/barbell-lying-triceps-extension-skull-crusher',
  }),
  ex({
    id: 'russian-twist',
    canonicalName: 'Russian Twist',
    aliases: [],
    bodyParts: ['core'],
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    movementPattern: 'core',
    equipmentSlots: [],
    instructions: [
      'Sit with knees bent, torso leaned back slightly, feet off the floor.',
      'Rotate your torso side to side, touching the floor beside your hips.',
    ],
    apiExerciseId: 'Russian_Twist',
    gymGifsId: 'abs/russian-twist',
  }),
];

// Custom (user-created) exercises are merged in at the call sites that read
// this catalog together with `state.customExercises.list` -- see
// lib/fitness/exerciseUtils.js's getAllExercises().
export function findExerciseById(id, extra = []) {
  return EXERCISE_CATALOG.find((e) => e.id === id) || extra.find((e) => e.id === id) || null;
}
