// lib/seed-data.js — seed content for Dallen's Math Notes. This only appears the
// first time a user has no saved data yet; real edits live in KV/localStorage.
export const TRACKER_SEED = [
  {
    id: 'algtop', name: 'Algebraic Topology', glyph: 'π₁', nickname: 'Alg Top',
    assignments: [
      { id: 'at1', title: 'Problem Set 3 — Van Kampen & pushouts', due: '2026-08-10', status: 'doing' },
      { id: 'at2', title: 'Problem Set 4 — CW complexes', due: '2026-08-24', status: 'todo' },
      { id: 'at3', title: 'Problem Set 2 — Homotopy lifting', due: '2026-07-28', status: 'done' },
    ],
    doc: `# Chapter 1 — Fundamentals

## Van Kampen's Theorem

If $X = U \\cup V$ with $U, V$ open and path-connected and $U \\cap V$ path-connected, then $\\pi_1(X) \\cong \\pi_1(U) *_{\\pi_1(U\\cap V)} \\pi_1(V)$.

Build the pushout of groupoids induced by the cover, then pass to fundamental groups — the amalgam records loops that stay in $U$, stay in $V$, or cross through $U \\cap V$.

## Fundamental group of the circle

$\\pi_1(S^1) \\cong \\mathbb{Z}$, generated by the loop winding once around.

Use the covering $p: \\mathbb{R} \\to S^1$, $t \\mapsto e^{2\\pi i t}$; paths and homotopies lift uniquely, and the winding number gives the isomorphism.

## CW complex

A space built inductively by attaching $n$-cells $D^n$ along maps $\\partial D^n \\to X^{(n-1)}$.

Keep re-deriving van Kampen from the groupoid version until it's obvious why $U \\cap V$ needs to be connected — the group version hides it.
`,
  },
  {
    id: 'meastheory', name: 'Measure Theory', glyph: '∫dμ', nickname: 'Measure',
    assignments: [
      { id: 'mt1', title: 'Problem Set 2 — Outer measures', due: '2026-08-05', status: 'todo' },
      { id: 'mt2', title: 'Problem Set 1 — σ-algebras', due: '2026-07-27', status: 'doing' },
    ],
    doc: `# Chapter 1 — Fundamentals

## Carathéodory Extension Theorem

A premeasure $\\mu_0$ on an algebra $\\mathcal{A}$ extends to a measure on $\\sigma(\\mathcal{A})$.

Define an outer measure $\\mu^*$ via countable covers by elements of $\\mathcal{A}$; the $\\mu^*$-measurable sets (Carathéodory criterion) form a $\\sigma$-algebra on which $\\mu^*$ is countably additive.

## Dominated Convergence Theorem

If $f_n \\to f$ a.e. and $|f_n| \\le g$ with $g$ integrable, then $\\int f_n \\to \\int f$.

Apply Fatou's lemma to $g - f_n$ and $g + f_n$ at once, squeezing $\\int f$ between $\\liminf$ and $\\limsup$ of $\\int f_n$.

## Fatou's Lemma

For nonnegative measurable $f_n$, $\\int \\liminf f_n \\le \\liminf \\int f_n$.

Key idea: apply monotone convergence to $g_n = \\inf_{k \\ge n} f_k$, which increases to $\\liminf f_n$.
`,
  },
  {
    id: 'chern', name: 'Chern Classes — Research', glyph: 'c(E)', nickname: 'Chern',
    assignments: [
      { id: 'ch1', title: 'Read Milnor–Stasheff ch. 14', due: '2026-08-01', status: 'todo' },
      { id: 'ch2', title: 'Draft: splitting principle writeup', due: '2026-08-15', status: 'todo' },
      { id: 'ch3', title: 'Meeting notes — advisor check-in', due: '2026-07-25', status: 'doing' },
    ],
    doc: `# Chapter 1 — Fundamentals

## Whitney Sum Formula

$c(E \\oplus F) = c(E) \\smile c(F)$ in $H^*(X)$.

Follows from the splitting principle: pull back to a space where both bundles split into line bundles, where the formula is a product of first Chern classes.

## Splitting Principle

For a vector bundle $E \\to X$ there is $f: F(E) \\to X$ with $f^*$ injective on cohomology and $f^*E$ a sum of line bundles.

Key idea: build $F(E)$ as the flag bundle of $E$; Leray–Hirsch gives the injectivity.

Research thread: does the splitting-principle argument generalise cleanly to equivariant Chern classes? Ask advisor Tuesday.
`,
  },
];
