// lib/bible/books.js — the 66-book canonical table backing lib/bible/refs.js.
// `code` is the 3-letter USFM/OSIS book code api.bible's passage-id format
// needs (e.g. "GEN.1.1-GEN.1.2"); `abbr` is a short list of common
// abbreviations a reference parser needs to recognise beyond the full name
// itself (refs.js normalizes away spaces/periods/case before comparing, so
// "1 Cor", "1Cor", "1cor." all match the same "1cor" alias).
export const BOOKS = [
  { name: 'Genesis', code: 'GEN', abbr: ['gen', 'ge', 'gn'] },
  { name: 'Exodus', code: 'EXO', abbr: ['exo', 'ex', 'exod'] },
  { name: 'Leviticus', code: 'LEV', abbr: ['lev', 'le', 'lv'] },
  { name: 'Numbers', code: 'NUM', abbr: ['num', 'nu', 'nm', 'nb'] },
  { name: 'Deuteronomy', code: 'DEU', abbr: ['deut', 'deu', 'dt'] },
  { name: 'Joshua', code: 'JOS', abbr: ['josh', 'jos', 'jsh'] },
  { name: 'Judges', code: 'JDG', abbr: ['judg', 'jdg', 'jg'] },
  { name: 'Ruth', code: 'RUT', abbr: ['ruth', 'rut', 'rth'] },
  { name: '1 Samuel', code: '1SA', abbr: ['1sam', '1sa', '1s'] },
  { name: '2 Samuel', code: '2SA', abbr: ['2sam', '2sa', '2s'] },
  { name: '1 Kings', code: '1KI', abbr: ['1kgs', '1ki', '1k'] },
  { name: '2 Kings', code: '2KI', abbr: ['2kgs', '2ki', '2k'] },
  { name: '1 Chronicles', code: '1CH', abbr: ['1chr', '1ch'] },
  { name: '2 Chronicles', code: '2CH', abbr: ['2chr', '2ch'] },
  { name: 'Ezra', code: 'EZR', abbr: ['ezra', 'ezr'] },
  { name: 'Nehemiah', code: 'NEH', abbr: ['neh'] },
  { name: 'Esther', code: 'EST', abbr: ['esth', 'est'] },
  { name: 'Job', code: 'JOB', abbr: ['job', 'jb'] },
  { name: 'Psalm', code: 'PSA', abbr: ['ps', 'psa', 'psalm', 'psalms', 'pss'] },
  { name: 'Proverbs', code: 'PRO', abbr: ['prov', 'pro', 'pr'] },
  { name: 'Ecclesiastes', code: 'ECC', abbr: ['eccl', 'ecc', 'ec'] },
  { name: 'Song of Solomon', code: 'SNG', abbr: ['song', 'sos', 'ss', 'songofsolomon', 'songofsongs'] },
  { name: 'Isaiah', code: 'ISA', abbr: ['isa', 'is'] },
  { name: 'Jeremiah', code: 'JER', abbr: ['jer', 'je'] },
  { name: 'Lamentations', code: 'LAM', abbr: ['lam', 'la'] },
  { name: 'Ezekiel', code: 'EZK', abbr: ['ezek', 'eze', 'ezk'] },
  { name: 'Daniel', code: 'DAN', abbr: ['dan', 'da'] },
  { name: 'Hosea', code: 'HOS', abbr: ['hos', 'ho'] },
  { name: 'Joel', code: 'JOL', abbr: ['joel', 'jl'] },
  { name: 'Amos', code: 'AMO', abbr: ['amos', 'am'] },
  { name: 'Obadiah', code: 'OBA', abbr: ['obad', 'oba', 'ob'] },
  { name: 'Jonah', code: 'JON', abbr: ['jonah', 'jon'] },
  { name: 'Micah', code: 'MIC', abbr: ['mic', 'mc'] },
  { name: 'Nahum', code: 'NAM', abbr: ['nah', 'na'] },
  { name: 'Habakkuk', code: 'HAB', abbr: ['hab', 'hb'] },
  { name: 'Zephaniah', code: 'ZEP', abbr: ['zeph', 'zep', 'zp'] },
  { name: 'Haggai', code: 'HAG', abbr: ['hag', 'hg'] },
  { name: 'Zechariah', code: 'ZEC', abbr: ['zech', 'zec', 'zc'] },
  { name: 'Malachi', code: 'MAL', abbr: ['mal', 'ml'] },
  { name: 'Matthew', code: 'MAT', abbr: ['matt', 'mat', 'mt'] },
  { name: 'Mark', code: 'MRK', abbr: ['mark', 'mrk', 'mk', 'mr'] },
  { name: 'Luke', code: 'LUK', abbr: ['luke', 'luk', 'lk'] },
  { name: 'John', code: 'JHN', abbr: ['john', 'jhn', 'jn'] },
  { name: 'Acts', code: 'ACT', abbr: ['acts', 'act', 'ac'] },
  { name: 'Romans', code: 'ROM', abbr: ['rom', 'ro', 'rm'] },
  { name: '1 Corinthians', code: '1CO', abbr: ['1cor', '1co'] },
  { name: '2 Corinthians', code: '2CO', abbr: ['2cor', '2co'] },
  { name: 'Galatians', code: 'GAL', abbr: ['gal', 'ga'] },
  { name: 'Ephesians', code: 'EPH', abbr: ['eph'] },
  { name: 'Philippians', code: 'PHP', abbr: ['phil', 'php'] },
  { name: 'Colossians', code: 'COL', abbr: ['col'] },
  { name: '1 Thessalonians', code: '1TH', abbr: ['1thess', '1th'] },
  { name: '2 Thessalonians', code: '2TH', abbr: ['2thess', '2th'] },
  { name: '1 Timothy', code: '1TI', abbr: ['1tim', '1ti'] },
  { name: '2 Timothy', code: '2TI', abbr: ['2tim', '2ti'] },
  { name: 'Titus', code: 'TIT', abbr: ['titus', 'tit'] },
  { name: 'Philemon', code: 'PHM', abbr: ['philem', 'phm'] },
  { name: 'Hebrews', code: 'HEB', abbr: ['heb'] },
  { name: 'James', code: 'JAS', abbr: ['jas', 'jm'] },
  { name: '1 Peter', code: '1PE', abbr: ['1pet', '1pe'] },
  { name: '2 Peter', code: '2PE', abbr: ['2pet', '2pe'] },
  { name: '1 John', code: '1JN', abbr: ['1john', '1jn'] },
  { name: '2 John', code: '2JN', abbr: ['2john', '2jn'] },
  { name: '3 John', code: '3JN', abbr: ['3john', '3jn'] },
  { name: 'Jude', code: 'JUD', abbr: ['jude', 'jd'] },
  { name: 'Revelation', code: 'REV', abbr: ['rev', 're'] },
];
