// lib/bible/books.js — the 66-book canonical table backing lib/bible/refs.js
// and the Reader's book/chapter browser. `code` is the 3-letter USFM/OSIS
// book code api.bible's passage-id format needs (e.g. "GEN.1.1-GEN.1.2");
// `abbr` is a short list of common abbreviations a reference parser needs
// to recognise beyond the full name itself (refs.js normalizes away
// spaces/periods/case before comparing, so "1 Cor", "1Cor", "1cor." all
// match the same "1cor" alias). `chapters` is the book's total chapter
// count -- the same across virtually every English translation, since
// chapter/verse divisions aren't part of what a translation changes -- used
// to build the chapter picker and to know when Next/Prev should roll over
// into the next or previous book.
export const BOOKS = [
  { name: 'Genesis', code: 'GEN', abbr: ['gen', 'ge', 'gn'], chapters: 50 },
  { name: 'Exodus', code: 'EXO', abbr: ['exo', 'ex', 'exod'], chapters: 40 },
  { name: 'Leviticus', code: 'LEV', abbr: ['lev', 'le', 'lv'], chapters: 27 },
  { name: 'Numbers', code: 'NUM', abbr: ['num', 'nu', 'nm', 'nb'], chapters: 36 },
  { name: 'Deuteronomy', code: 'DEU', abbr: ['deut', 'deu', 'dt'], chapters: 34 },
  { name: 'Joshua', code: 'JOS', abbr: ['josh', 'jos', 'jsh'], chapters: 24 },
  { name: 'Judges', code: 'JDG', abbr: ['judg', 'jdg', 'jg'], chapters: 21 },
  { name: 'Ruth', code: 'RUT', abbr: ['ruth', 'rut', 'rth'], chapters: 4 },
  { name: '1 Samuel', code: '1SA', abbr: ['1sam', '1sa', '1s'], chapters: 31 },
  { name: '2 Samuel', code: '2SA', abbr: ['2sam', '2sa', '2s'], chapters: 24 },
  { name: '1 Kings', code: '1KI', abbr: ['1kgs', '1ki', '1k'], chapters: 22 },
  { name: '2 Kings', code: '2KI', abbr: ['2kgs', '2ki', '2k'], chapters: 25 },
  { name: '1 Chronicles', code: '1CH', abbr: ['1chr', '1ch'], chapters: 29 },
  { name: '2 Chronicles', code: '2CH', abbr: ['2chr', '2ch'], chapters: 36 },
  { name: 'Ezra', code: 'EZR', abbr: ['ezra', 'ezr'], chapters: 10 },
  { name: 'Nehemiah', code: 'NEH', abbr: ['neh'], chapters: 13 },
  { name: 'Esther', code: 'EST', abbr: ['esth', 'est'], chapters: 10 },
  { name: 'Job', code: 'JOB', abbr: ['job', 'jb'], chapters: 42 },
  { name: 'Psalm', code: 'PSA', abbr: ['ps', 'psa', 'psalm', 'psalms', 'pss'], chapters: 150 },
  { name: 'Proverbs', code: 'PRO', abbr: ['prov', 'pro', 'pr'], chapters: 31 },
  { name: 'Ecclesiastes', code: 'ECC', abbr: ['eccl', 'ecc', 'ec'], chapters: 12 },
  { name: 'Song of Solomon', code: 'SNG', abbr: ['song', 'sos', 'ss', 'songofsolomon', 'songofsongs'], chapters: 8 },
  { name: 'Isaiah', code: 'ISA', abbr: ['isa', 'is'], chapters: 66 },
  { name: 'Jeremiah', code: 'JER', abbr: ['jer', 'je'], chapters: 52 },
  { name: 'Lamentations', code: 'LAM', abbr: ['lam', 'la'], chapters: 5 },
  { name: 'Ezekiel', code: 'EZK', abbr: ['ezek', 'eze', 'ezk'], chapters: 48 },
  { name: 'Daniel', code: 'DAN', abbr: ['dan', 'da'], chapters: 12 },
  { name: 'Hosea', code: 'HOS', abbr: ['hos', 'ho'], chapters: 14 },
  { name: 'Joel', code: 'JOL', abbr: ['joel', 'jl'], chapters: 3 },
  { name: 'Amos', code: 'AMO', abbr: ['amos', 'am'], chapters: 9 },
  { name: 'Obadiah', code: 'OBA', abbr: ['obad', 'oba', 'ob'], chapters: 1 },
  { name: 'Jonah', code: 'JON', abbr: ['jonah', 'jon'], chapters: 4 },
  { name: 'Micah', code: 'MIC', abbr: ['mic', 'mc'], chapters: 7 },
  { name: 'Nahum', code: 'NAM', abbr: ['nah', 'na'], chapters: 3 },
  { name: 'Habakkuk', code: 'HAB', abbr: ['hab', 'hb'], chapters: 3 },
  { name: 'Zephaniah', code: 'ZEP', abbr: ['zeph', 'zep', 'zp'], chapters: 3 },
  { name: 'Haggai', code: 'HAG', abbr: ['hag', 'hg'], chapters: 2 },
  { name: 'Zechariah', code: 'ZEC', abbr: ['zech', 'zec', 'zc'], chapters: 14 },
  { name: 'Malachi', code: 'MAL', abbr: ['mal', 'ml'], chapters: 4 },
  { name: 'Matthew', code: 'MAT', abbr: ['matt', 'mat', 'mt'], chapters: 28 },
  { name: 'Mark', code: 'MRK', abbr: ['mark', 'mrk', 'mk', 'mr'], chapters: 16 },
  { name: 'Luke', code: 'LUK', abbr: ['luke', 'luk', 'lk'], chapters: 24 },
  { name: 'John', code: 'JHN', abbr: ['john', 'jhn', 'jn'], chapters: 21 },
  { name: 'Acts', code: 'ACT', abbr: ['acts', 'act', 'ac'], chapters: 28 },
  { name: 'Romans', code: 'ROM', abbr: ['rom', 'ro', 'rm'], chapters: 16 },
  { name: '1 Corinthians', code: '1CO', abbr: ['1cor', '1co'], chapters: 16 },
  { name: '2 Corinthians', code: '2CO', abbr: ['2cor', '2co'], chapters: 13 },
  { name: 'Galatians', code: 'GAL', abbr: ['gal', 'ga'], chapters: 6 },
  { name: 'Ephesians', code: 'EPH', abbr: ['eph'], chapters: 6 },
  { name: 'Philippians', code: 'PHP', abbr: ['phil', 'php'], chapters: 4 },
  { name: 'Colossians', code: 'COL', abbr: ['col'], chapters: 4 },
  { name: '1 Thessalonians', code: '1TH', abbr: ['1thess', '1th'], chapters: 5 },
  { name: '2 Thessalonians', code: '2TH', abbr: ['2thess', '2th'], chapters: 3 },
  { name: '1 Timothy', code: '1TI', abbr: ['1tim', '1ti'], chapters: 6 },
  { name: '2 Timothy', code: '2TI', abbr: ['2tim', '2ti'], chapters: 4 },
  { name: 'Titus', code: 'TIT', abbr: ['titus', 'tit'], chapters: 3 },
  { name: 'Philemon', code: 'PHM', abbr: ['philem', 'phm'], chapters: 1 },
  { name: 'Hebrews', code: 'HEB', abbr: ['heb'], chapters: 13 },
  { name: 'James', code: 'JAS', abbr: ['jas', 'jm'], chapters: 5 },
  { name: '1 Peter', code: '1PE', abbr: ['1pet', '1pe'], chapters: 5 },
  { name: '2 Peter', code: '2PE', abbr: ['2pet', '2pe'], chapters: 3 },
  { name: '1 John', code: '1JN', abbr: ['1john', '1jn'], chapters: 5 },
  { name: '2 John', code: '2JN', abbr: ['2john', '2jn'], chapters: 1 },
  { name: '3 John', code: '3JN', abbr: ['3john', '3jn'], chapters: 1 },
  { name: 'Jude', code: 'JUD', abbr: ['jude', 'jd'], chapters: 1 },
  { name: 'Revelation', code: 'REV', abbr: ['rev', 're'], chapters: 22 },
];
